import React, { createContext, useContext, useMemo } from "react";

const CountyCityContext = createContext();

const CountyCityProvider = ({ children }) => {
  const countiesAndCities = [
    { id: 1, name: "Alba", value: "Alba Iulia" },
    { id: 2, name: "Alba", value: "Aiud" },
    { id: 3, name: "Alba", value: "Blaj" },
    { id: 4, name: "Alba", value: "Cîmpeni" },
    { id: 5, name: "Alba", value: "Zlatna" },
    { id: 6, name: "Alba", value: "Ocna Mures" },
    { id: 7, name: "Arad", value: "Arad" },
    { id: 8, name: "Arad", value: "Ineu" },
    { id: 9, name: "Arad", value: "Chisineu-Cris" },
    { id: 10, name: "Arad", value: "Lipova" },
    { id: 11, name: "Arad", value: "Pecica" },
    { id: 12, name: "Arad", value: "Curtici" },
    { id: 13, name: "Arges", value: "Pitesti" },
    { id: 14, name: "Arges", value: "Campulung" },
    { id: 15, name: "Arges", value: "Curtea de Arges" },
    { id: 16, name: "Arges", value: "Mioveni" },
    { id: 17, name: "Arges", value: "Topoloveni" },
    { id: 18, name: "Arges", value: "Stefanesti" },
    { id: 19, name: "Bacau", value: "Bacau" },
    { id: 20, name: "Bacau", value: "Onesti" },
    { id: 21, name: "Bacau", value: "Moinesti" },
    { id: 22, name: "Bacau", value: "Comanesti" },
    { id: 23, name: "Bacau", value: "Buhusi" },
    { id: 24, name: "Bacau", value: "Targu Ocna" },
    { id: 25, name: "Bihor", value: "Oradea" },
    { id: 26, name: "Bihor", value: "Beius" },
    { id: 27, name: "Bihor", value: "Salonta" },
    { id: 28, name: "Bihor", value: "Marghita" },
    { id: 29, name: "Bihor", value: "Valea lui Mihai" },
    { id: 30, name: "Bihor", value: "Alesd" },
    { id: 31, name: "Bistrita-Nasaud", value: "Bistrita" },
    { id: 32, name: "Bistrita-Nasaud", value: "Nasaud" },
    { id: 33, name: "Bistrita-Nasaud", value: "Beclean" },
    { id: 34, name: "Bistrita-Nasaud", value: "Sangeorz-Bai" },
    { id: 35, name: "Botosani", value: "Botosani" },
    { id: 36, name: "Botosani", value: "Dorohoi" },
    { id: 37, name: "Botosani", value: "Saveni" },
    { id: 38, name: "Botosani", value: "Darabani" },
    { id: 39, name: "Botosani", value: "Flamanzi" },
    { id: 40, name: "Brasov", value: "Brasov" },
    { id: 41, name: "Brasov", value: "Fagaras" },
    { id: 42, name: "Brasov", value: "Rupea" },
    { id: 43, name: "Brasov", value: "Codlea" },
    { id: 44, name: "Brasov", value: "Sacele" },
    { id: 45, name: "Brasov", value: "Predeal" },
    { id: 46, name: "Brasov", value: "Zarnesti" },
    { id: 47, name: "Braila", value: "Braila" },
    { id: 48, name: "Braila", value: "Faurei" },
    { id: 49, name: "Braila", value: "Ianca" },
    { id: 50, name: "Braila", value: "Insuratei" },
    { id: 51, name: "Buzau", value: "Buzau" },
    { id: 52, name: "Buzau", value: "Ramnicu Sarat" },
    { id: 53, name: "Buzau", value: "Nehoiu" },
    { id: 54, name: "Buzau", value: "Patarlagele" },
    { id: 55, name: "Buzau", value: "Pogoanele" },
    { id: 56, name: "Caras-Severin", value: "Resita" },
    { id: 57, name: "Caras-Severin", value: "Caransebes" },
    { id: 58, name: "Caras-Severin", value: "Bocsa" },
    { id: 59, name: "Caras-Severin", value: "Oravita" },
    { id: 60, name: "Caras-Severin", value: "Anina" },
    { id: 61, name: "Caras-Severin", value: "Baile Herculane" },
    { id: 62, name: "Caras-Severin", value: "Moldova Noua" },
    { id: 63, name: "Calarasi", value: "Calarasi" },
    { id: 64, name: "Calarasi", value: "Oltenita" },
    { id: 65, name: "Calarasi", value: "Lehliu Gara" },
    { id: 66, name: "Calarasi", value: "Budesti" },
    { id: 67, name: "Calarasi", value: "Fundulea" },
    { id: 68, name: "Cluj", value: "Cluj-Napoca" },
    { id: 69, name: "Cluj", value: "Turda" },
    { id: 70, name: "Cluj", value: "Dej" },
    { id: 71, name: "Cluj", value: "Gherla" },
    { id: 72, name: "Cluj", value: "Huedin" },
    { id: 73, name: "Constanta", value: "Constanta" },
    { id: 74, name: "Constanta", value: "Mangalia" },
    { id: 75, name: "Constanta", value: "Medgidia" },
    { id: 76, name: "Constanta", value: "Navodari" },
    { id: 77, name: "Constanta", value: "Cernavoda" },
    { id: 78, name: "Constanta", value: "Ovidiu" },
    { id: 79, name: "Constanta", value: "Eforie" },
    { id: 80, name: "Covasna", value: "Sfantu Gheorghe" },
    { id: 81, name: "Covasna", value: "Targu Secuiesc" },
    { id: 82, name: "Covasna", value: "Covasna" },
    { id: 83, name: "Covasna", value: "Baraolt" },
    { id: 84, name: "Covasna", value: "Intorsura Buzaului" },
    { id: 85, name: "Dambovita", value: "Targoviste" },
    { id: 86, name: "Dambovita", value: "Targoviste" },
    { id: 87, name: "Dambovita", value: "Moreni" },
    { id: 88, name: "Dambovita", value: "Pucioasa" },
    { id: 89, name: "Dambovita", value: "Fieni" },
    { id: 90, name: "Dambovita", value: "Titu" },
    { id: 91, name: "Dambovita", value: "Gaesti" },
    { id: 92, name: "Dolj", value: "Craiova" },
    { id: 93, name: "Dolj", value: "Bailesti" },
    { id: 94, name: "Dolj", value: "Calafat" },
    { id: 95, name: "Dolj", value: "Filiasi" },
    { id: 96, name: "Dolj", value: "Dabuleni" },
    { id: 97, name: "Dolj", value: "Segarcea" },
    { id: 98, name: "Galati", value: "Galati" },
    { id: 99, name: "Galati", value: "Tecuci" },
    { id: 100, name: "Galati", value: "Targu Bujor" },
    { id: 101, name: "Galati", value: "Beresti" },
    { id: 102, name: "Giurgiu", value: "Giurgiu" },
    { id: 103, name: "Giurgiu", value: "Bolintin-Vale" },
    { id: 104, name: "Giurgiu", value: "Mihailesti" },
    { id: 105, name: "Gorj", value: "Targu Jiu" },
    { id: 106, name: "Gorj", value: "Motru" },
    { id: 107, name: "Gorj", value: "Rovinari" },
    { id: 108, name: "Gorj", value: "Targu Carbunesti" },
    { id: 109, name: "Gorj", value: "Tismana" },
    { id: 110, name: "Gorj", value: "Novaci" },
    { id: 111, name: "Gorj", value: "Bumbesti-Jiu" },
    { id: 112, name: "Harghita", value: "Miercurea Ciuc" },
    { id: 113, name: "Harghita", value: "Odorheiu Secuiesc" },
    { id: 114, name: "Harghita", value: "Gheorgheni" },
    { id: 115, name: "Harghita", value: "Toplita" },
    { id: 116, name: "Harghita", value: "Cristuru Secuiesc" },
    { id: 117, name: "Harghita", value: "Vlahita" },
    { id: 118, name: "Harghita", value: "Balan" },
    { id: 119, name: "Hunedoara", value: "Deva" },
    { id: 120, name: "Hunedoara", value: "Hunedoara" },
    { id: 121, name: "Hunedoara", value: "Petrosani" },
    { id: 122, name: "Hunedoara", value: "Vulcan" },
    { id: 123, name: "Hunedoara", value: "Lupeni" },
    { id: 124, name: "Hunedoara", value: "Brad" },
    { id: 125, name: "Hunedoara", value: "Orastie" },
    { id: 126, name: "Hunedoara", value: "Simeria" },
    { id: 127, name: "Hunedoara", value: "Uricani" },
    { id: 128, name: "Hunedoara", value: "Hateg" },
    { id: 129, name: "Ialomita", value: "Slobozia" },
    { id: 130, name: "Ialomita", value: "Fetesti" },
    { id: 131, name: "Ialomita", value: "Urziceni" },
    { id: 132, name: "Ialomita", value: "Tandarei" },
    { id: 133, name: "Ialomita", value: "Amara" },
    { id: 134, name: "Iasi", value: "Iasi" },
    { id: 135, name: "Iasi", value: "Pascani" },
    { id: 136, name: "Iasi", value: "Harlau" },
    { id: 137, name: "Iasi", value: "Targu Frumos" },
    { id: 138, name: "Iasi", value: "Podu Iloaiei" },
    { id: 139, name: "Ilfov", value: "Buftea" },
    { id: 140, name: "Ilfov", value: "Otopeni" },
    { id: 141, name: "Ilfov", value: "Voluntari" },
    { id: 142, name: "Ilfov", value: "Pantelimon" },
    { id: 143, name: "Ilfov", value: "Popesti-Leordeni" },
    { id: 144, name: "Ilfov", value: "Bragadiru" },
    { id: 145, name: "Ilfov", value: "Chitila" },
    { id: 146, name: "Ilfov", value: "Magurele" },
    { id: 147, name: "Ilfov", value: "Snagov" },
    { id: 148, name: "Ilfov", value: "Cernica" },
    { id: 149, name: "Ilfov", value: "Dobroesti" },
    { id: 150, name: "Ilfov", value: "Corbeanca" },
    { id: 151, name: "Ilfov", value: "Domnesti" },
  ];

  const getCitiesByCounty = (countyName) => {
    const county = countiesAndCities.find((item) => item.name === countyName);
    return county ? county.value : [];
  };

  const contextValue = useMemo(() => ({ countiesAndCities, getCitiesByCounty }), [countiesAndCities]);

  return <RomaniaCitiesContext.Provider value={contextValue}>{children}</RomaniaCitiesContext.Provider>;
};

const useRomaniaCities = () => useContext(RomaniaCitiesContext);

export { RomaniaCitiesProvider, useRomaniaCities };