import React, { createContext, useContext, useMemo } from "react";

const StudentAttributesContext = createContext();

const StudentAttributesProvider = ({ children }) => {
  const features = [
    { id: 1, name: "Gen", value: "Masculin" },
    { id: 2, name: "Gen", value: "Feminin" },
    { id: 3, name: "Gen", value: "Altul" },
    { id: 4, name: "Ocupatie", value: "Part-Time Job" },
    { id: 5, name: "Ocupatie", value: "Full-Time Job" },
    { id: 6, name: "Ocupatie", value: "Student" },
    { id: 7, name: "An de studiu", value: "1" },
    { id: 8, name: "An de studiu", value: "2" },
    { id: 9, name: "An de studiu", value: "3" },
    { id: 10, name: "An de studiu", value: "4" },
    { id: 11, name: "An de studiu", value: "5" },
    { id: 12, name: "An de studiu", value: "6" },
    { id: 13, name: "Religie", value: "Ortodox" },
    { id: 14, name: "Religie", value: "Ronano-Catolic" },
    { id: 15, name: "Religie", value: "Greco-Catolic" },
    { id: 16, name: "Religie", value: "Calvinist" },
    { id: 17, name: "Religie", value: "Luteran" },
    { id: 18, name: "Religie", value: "Creștin Penticostal" },
    { id: 19, name: "Religie", value: "Islam" },
    { id: 20, name: "Religie", value: "Iudaism" },
    { id: 21, name: "Religie", value: "Baptist" },
    { id: 22, name: "Religie", value: "Ateism/Agnosticism" },
    { id: 23, name: "Religie", value: "Adventist" },
    { id: 24, name: "Religie", value: "Martorii lui Iehova" },
    { id: 25, name: "Religie", value: "Budism" },
    { id: 26, name: "Religie", value: "Hinduism" },
    { id: 27, name: "Religie", value: "Altul" },
    { id: 28, name: "Preferinte Alimentare", value: "Fără Preferințe" },
    { id: 29, name: "Preferinte Alimentare", value: "Vegetarian" },
    { id: 30, name: "Preferinte Alimentare", value: "Vegan" },
    { id: 31, name: "Preferinte Alimentare", value: "Pescarian" },
    { id: 32, name: "Preferinte Alimentare", value: "Fără Gluten" },
    { id: 33, name: "Preferinte Alimentare", value: "Fără Lactoză" },
    { id: 34, name: "Preferinte Alimentare", value: "Keto" },
    { id: 35, name: "Preferinte Alimentare", value: "Prietenos cu Diabetici" },
    { id: 36, name: "Preferinte Alimentare", value: "Halal" },
    { id: 37, name: "Preferinte Alimentare", value: "Kosher" },
    { id: 38, name: "Preferinte Alimentare", value: "Organic" },
    { id: 39, name: "Preferinte Alimentare", value: "Altul" },
    { id: 40, name: "Alergii", value: "Fără Alergii" },
    { id: 41, name: "Alergii", value: "Alune/Nuci" },
    { id: 42, name: "Alergii", value: "Lactate" },
    { id: 43, name: "Alergii", value: "Ouă" },
    { id: 44, name: "Alergii", value: "Grâu" },
    { id: 45, name: "Alergii", value: "Soia" },
    { id: 46, name: "Alergii", value: "Pește" },
    { id: 47, name: "Alergii", value: "Polen" },
    { id: 48, name: "Alergii", value: "Acarieni" },
    { id: 49, name: "Alergii", value: "Mucegai" },
    { id: 50, name: "Alergii", value: "Pisici" },
    { id: 51, name: "Alergii", value: "Câini" },
    { id: 52, name: "Alergii", value: "Latex" },
    { id: 53, name: "Alergii", value: "Parfumuri" },
    { id: 54, name: "Alergii", value: "Produse Cosmetice" },
    { id: 55, name: "Alergii", value: "Detergenți și Săpunuri" },
    { id: 56, name: "Alergii", value: "Înțepături de Albine" },
    { id: 57, name: "Alergii", value: "Înțepături de Viespe" },
    { id: 58, name: "Alergii", value: "Înțepături de Furnici" },
    { id: 59, name: "Alergii", value: "Medicamente" },
    { id: 60, name: "Alergii", value: "Altul" },
    { id: 61, name: "Ore de Somn", value: "Dimineața devreme" },
    { id: 62, name: "Ore de Somn", value: "Noaptea târziu" },
    { id: 63, name: "Ore de Somn", value: "Flexibil" },
    { id: 64, name: "Ore de Somn", value: "Altul" },
    { id: 65, name: "Obiceiuri de Fumat", value: "Fumător" },
    { id: 66, name: "Obiceiuri de Fumat", value: "Nefumător" },
    { id: 67, name: "Obiceiuri de Fumat", value: "Nu contează" },
    { id: 68, name: "Consum de Alcool", value: "Regulat" },
    { id: 69, name: "Consum de Alcool", value: "Social" },
    { id: 70, name: "Consum de Alcool", value: "Rar" },
    { id: 71, name: "Consum de Alcool", value: "Niciodată" },
    { id: 72, name: "Deținere de Animale", value: "Nu" },
    { id: 73, name: "Deținere de Animale", value: "Pisică" },
    { id: 74, name: "Deținere de Animale", value: "Câine" },
    { id: 75, name: "Deținere de Animale", value: "Pasări" },
    { id: 76, name: "Deținere de Animale", value: "Pești" },
    { id: 77, name: "Deținere de Animale", value: "Rozătoare" },
    { id: 78, name: "Deținere de Animale", value: "Altu" },
    { id: 79, name: "Preferințe pentru Animale", value: "Îmi plac animalele" },
    { id: 80, name: "Preferințe pentru Animale", value: "Nu îmi plac animalele" },
    { id: 81, name: "Preferințe pentru Animale", value: "Alergic" },
    { id: 82, name: "Preferințe pentru Animale", value: "Fără preferințe" },
    { id: 83, name: "Toleranță la Zgomot", value: "Liniște" },
    { id: 84, name: "Toleranță la Zgomot", value: "Moderat" },
    { id: 85, name: "Toleranță la Zgomot", value: "Nu contează" },
    { id: 86, name: "Nivel de Curățenie", value: "Foarte Curat" },
    { id: 87, name: "Nivel de Curățenie", value: "Moderat" },
    { id: 88, name: "Nivel de Curățenie", value: "Relaxat" },
    { id: 89, name: "Obiceiuri de Gătit", value: "Iubesc să găteasc" },
    { id: 90, name: "Obiceiuri de Gătit", value: "Gătesc ocazional" },
    { id: 91, name: "Obiceiuri de Gătit", value: "Nu gătesc" },
    { id: 92, name: "Aranjament de Locuit Preferat", value: "Cameră Privată" },
    { id: 93, name: "Aranjament de Locuit Preferat", value: "Cameră Comună" },
    { id: 94, name: "Aranjament de Locuit Preferat", value: "Nu contează" },
    { id: 95, name: "Hobby-uri", value: "Desen" },
    { id: 96, name: "Hobby-uri", value: "Pictură" },
    { id: 97, name: "Hobby-uri", value: "Cântat" },
    { id: 98, name: "Hobby-uri", value: "Caligrafie" },
    { id: 99, name: "Hobby-uri", value: "Fotografie" },
    { id: 100, name: "Hobby-uri", value: "Design Grafic" },
    { id: 101, name: "Hobby-uri", value: "Cântat la un Instrument" },
    { id: 102, name: "Hobby-uri", value: "Tricotat/Croșetat" },
    { id: 103, name: "Hobby-uri", value: "Cusut/Design Vestimentar" },
    { id: 104, name: "Hobby-uri", value: "Dans" },
    { id: 105, name: "Hobby-uri", value: "Stand-up Comedy" },
    { id: 106, name: "Hobby-uri", value: "Trucuri de Magie" },
    { id: 107, name: "Hobby-uri", value: "Scris" },
    { id: 108, name: "Hobby-uri", value: "Citit" },
    { id: 109, name: "Hobby-uri", value: "Blogging" },
    { id: 110, name: "Hobby-uri", value: "Alergat/Jogging" },
    { id: 111, name: "Hobby-uri", value: "Yoga" },
    { id: 112, name: "Hobby-uri", value: "Pilates" },
    { id: 113, name: "Hobby-uri", value: "Înot" },
    { id: 114, name: "Hobby-uri", value: "Drumeții" },
    { id: 115, name: "Hobby-uri", value: "Ciclism" },
    { id: 116, name: "Hobby-uri", value: "Arte Marțiale" },
    { id: 117, name: "Hobby-uri", value: "Fotbal" },
    { id: 118, name: "Hobby-uri", value: "Baschet" },
    { id: 119, name: "Hobby-uri", value: "Volei" },
    { id: 120, name: "Hobby-uri", value: "Handbal" },
    { id: 121, name: "Hobby-uri", value: "Cățărat pe Stânci" },
    { id: 122, name: "Hobby-uri", value: "Gimnastică" },
    { id: 123, name: "Hobby-uri", value: "Gaming" },
    { id: 124, name: "Hobby-uri", value: "Programare/Codare" },
    { id: 125, name: "Hobby-uri", value: "Robotică" },
    { id: 126, name: "Hobby-uri", value: "VR" },
    { id: 127, name: "Hobby-uri", value: "Printare 3D" },
    { id: 128, name: "Hobby-uri", value: "Zbor cu Drone" },
    { id: 129, name: "Hobby-uri", value: "Gătit" },
    { id: 130, name: "Hobby-uri", value: "Copt" },
    { id: 131, name: "Hobby-uri", value: "Preparare Cafea" },
    { id: 132, name: "Hobby-uri", value: "Decorare Torturi" },
    { id: 133, name: "Hobby-uri", value: "Grădinărit" },
    { id: 134, name: "Hobby-uri", value: "Observare Păsări" },
    { id: 135, name: "Hobby-uri", value: "Camping" },
    { id: 136, name: "Hobby-uri", value: "Pescuit" },
    { id: 137, name: "Hobby-uri", value: "Geocaching" },
    { id: 138, name: "Hobby-uri", value: "Observare Stele" },
    { id: 139, name: "Hobby-uri", value: "Colecționare Timbre" },
    { id: 140, name: "Hobby-uri", value: "Colecționare Monede" },
    { id: 141, name: "Hobby-uri", value: "Colecționare Figuri de Acțiune" },
    { id: 142, name: "Hobby-uri", value: "Colecționare Viniluri" },
    { id: 143, name: "Hobby-uri", value: "Colecționare Fosile sau Roci" },
    { id: 144, name: "Hobby-uri", value: "Construcție de Modele" },
    { id: 145, name: "Hobby-uri", value: "Origami" },
    { id: 146, name: "Hobby-uri", value: "Mărgelit" },
    { id: 147, name: "Hobby-uri", value: "Puzzle-uri" },
    { id: 148, name: "Hobby-uri", value: "Șah" },
    { id: 149, name: "Hobby-uri", value: "Sudoku" },
    { id: 150, name: "Hobby-uri", value: "Călătorii" },
    { id: 151, name: "Hobby-uri", value: "Excursii cu Mașina" },
    { id: 152, name: "Hobby-uri", value: "Drumeții cu Rucsacul" },
    { id: 153, name: "Hobby-uri", value: "Vizionare de Filme" },
    { id: 154, name: "Hobby-uri", value: "Podcasting" },
    { id: 155, name: "Hobby-uri", value: "Creare de Conținut/Streaming" },
    { id: 156, name: "Hobby-uri", value: "Astrologie" },
    { id: 157, name: "Hobby-uri", value: "Cosplaying" },
    { id: 158, name: "Hobby-uri", value: "Parkour" },
    { id: 159, name: "Hobby-uri", value: "Altul" },
    { id: 160, name: "Rutine de Exerciții", value: "Merg la sală" },
    { id: 161, name: "Rutine de Exerciții", value: "Activități în aer liber" },
    { id: 162, name: "Rutine de Exerciții", value: "Nu fac exerciții în mod regulat" },
    { id: 163, name: "Obiceiuri Sociale", value: "Sociabil" },
    { id: 164, name: "Obiceiuri Sociale", value: "Introvertit" },
    { id: 165, name: "Obiceiuri Sociale", value: "Echilibrat" },
    { id: 166, name: "Genul Preferat al Colegului de Cameră", value: "Același Gen" },
    { id: 167, name: "Genul Preferat al Colegului de Cameră", value: "Fără Preferințe" },
    { id: 168, name: "Toleranță la Oaspeți", value: "Vizite Frecvente" },
    { id: 169, name: "Toleranță la Oaspeți", value: "Rareori" },
    { id: 170, name: "Toleranță la Oaspeți", value: "Fără Vizitatori" },
    { id: 171, name: "Mediu de Studiu", value: "Liniștit" },
    { id: 172, name: "Mediu de Studiu", value: "Colaborativ" },
    { id: 173, name: "Mediu de Studiu", value: "Fără Preferințe" },
    { id: 174, name: "Mijloc de Comunicare Preferat", value: "Text" },
    { id: 175, name: "Mijloc de Comunicare Preferat", value: "Apeluri" },
    { id: 176, name: "Mijloc de Comunicare Preferat", value: "Față-în-Față" },
    { id: 177, name: "Tip de Personalitate", value: "Introvertit" },
    { id: 178, name: "Tip de Personalitate", value: "Extrovertit" },
    { id: 179, name: "Stil de Rezolvare a Conflictelor", value: "Direct" },
    { id: 180, name: "Stil de Rezolvare a Conflictelor", value: "Pasiv" },
    { id: 181, name: "Stil de Rezolvare a Conflictelor", value: "Mediator" },

  ];

  const getById = (id) => features.find((item) => item.id === id);

  const contextValue = useMemo(() => ({ features, getById }), [features]);

  return <StudentAttributesContext.Provider value={contextValue}>{children}</StudentAttributesContext.Provider>;
};

const useData = () => useContext(StudentAttributesContext);

export { StudentAttributesProvider, useData };
